services:
  web:
    build:
      context: ./frontend
    ports:
      - "8080:80"

  api:
    build:
      context: ./backend
    ports:
      - "5000:5000"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"